### PR TITLE
Various CI fixes

### PR DESCRIPTION
**Pull request by iomaganaris**
- Use `nrn_requirements.txt` and `ci_requirements.txt` to install the necessary python packages for the NEURON installation
- If `ci_requirements.txt` doesn't exist (NEURON 8.2.3) then just install the current packages listed in it
- Install the NMODL required packages from `external/nmodl/requirements.txt`
- Upgrade from MacOS 11,12 to 12, 13
- Install `setuptools` for `Python 12` support
- Recursively clone submodules

## TODO

- [x] Port https://github.com/neuronsimulator/nrn/pull/2193 to `NEURON 8.2.3` to enable Python 3.12 support (handled in https://github.com/neuronsimulator/nrn/pull/2663)
- [x] fix segfault in Python 3.12 (fixed in https://github.com/neuronsimulator/nrn/pull/2695)

### CODE REVIEW

**Comment by JCGoran** [comment]
LGTM, now I think we just need to wait for a 8.2.x release which has full Python 3.12 support, after which we can merge this.

**Comment by pramodk** [comment]
Asking for clarity:  As 8.2.x tag/release could take some time (week[s]), do we have any other option to get this merged sooner and make CI green? i.e. using python 3.11 or MacOS-13 Or stick to MacOS 11 & 12 for some time?

**Comment by JCGoran** [comment]
In principle it should be doable as the MacOS runners come with a cached version of Python 3.11 (see for instance [here](https://github.com/actions/runner-images/blob/macos-13/20240114.1/images/macos/macos-13-Readme.md#user-content-python)), but I'm not 100% sure how to modify the CI config file to make it pass for all cases (tried using `setup-python` but it didn't work as expected as the run [failed](https://github.com/neuronsimulator/nrn-build-ci/actions/runs/7588944976), I think it should setup different versions of Python depending on the runner and not just use the same version for all of them).

**Review by JCGoran — APPROVED** [review]
Now that the CI actually passes, I think we can finally merge this.

**Pull request merged**
